# Generated by Django 2.1.2 on 2018-12-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181211_1546'),
        ('posts', '0003_auto_20181217_1411'),
    ]

    operations = [
    ]
