# Generated by Django 2.1.4 on 2018-12-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181217_1727'),
        ('posts', '0005_auto_20181217_1613'),
    ]

    operations = [
    ]
